### ISSUE TITLE
Unnecessary dependency on the `cpphs` library

### ISSUE THREAD

**Issue by asr** [jonaprieto/OnlineATPs#33]
It seems that the dependency on the `cpphs` _library_ is unnecessary.

**Comment by jonaprieto** [comment]
It's necessary. Check out this https://travis-ci.org/jonaprieto/OnlineATPs/jobs/157498887

**Comment by jonaprieto** [comment]
Thanks for noted.

**Comment by asr** [comment]
Which commit closed this issue?

**Comment by jonaprieto** [comment]
This https://github.com/jonaprieto/OnlineATPs/commit/8023acdc44a3813909ffebf69a7bab75c6b4a5f6
